use [DMA-CSD-V23_10511081]
GO

DROP TABLE Private_Customer
DROP TABLE Business_Customer
DROP TABLE SaleOrderLine
DROP TABLE Clothing
DROP TABLE Equipment
DROP TABLE GunReplica
DROP TABLE StockLine
DROP TABLE StockLocation
DROP TABLE PRODUCT
DROP TABLE SaleOrder
DROP TABLE Supplier
DROP TABLE Invoice
DROP TABLE Product
DROP TABLE Customer
DROP TABLE ZipCodeCity
DROP TABLE Country